import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css';
import Web3 from 'web3';
import { LSPFactory } from '@lukso/lsp-factory.js';
import { ERC725 } from '@erc725/erc725.js';
import 'isomorphic-fetch';
import erc725schema from '@erc725/erc725.js/schemas/LSP3UniversalProfileMetadata.json';


export default function Home() {


  const connectWallet = async (event) => {
    if (window.ethereum) {

      const web3 = new Web3(window.ethereum);
      const accounts = await web3.eth.requestAccounts();
      const UPAddress = "0x4977DDDF91bfd79534321DA43036bbbE1B2d934c";

      const RPC_ENDPOINT = 'https://rpc.l16.lukso.network';
      const IPFS_GATEWAY = 'https://2eff.lukso.dev/ipfs/';

      const provider = new Web3.providers.HttpProvider(RPC_ENDPOINT);
      const config = { ipfsGateway: IPFS_GATEWAY };

      async function fetchProfile(address) {
        try {
          const profile = new ERC725(erc725schema, address, provider, config);
          return await profile.fetchData('LSP3Profile');
        } catch (error) {
          return console.log('This is not an ERC725 Contract');
        }
      }

      fetchProfile(UPAddress).then((profileData) =>
        console.log(JSON.stringify(profileData, undefined, 2)),
      );

      const erc725 = new ERC725(erc725schema, UPAddress, provider, config);
      const add = await erc725.getOwner();
      console.log(add);


    } else {
      alert("Please install MetaMask");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Lukso Demo Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Lukso Demo Page
        </h3>

        <div className={styles.grid}>
          <button onClick={connectWallet} type="button" className="btn btn-secondary">Connect Lukso Wallet</button>
        </div>

      </main>

      <footer className={styles.footer}>
        Powered By Ayden lee
      </footer>
    </div >
  )
}
